apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-apache
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.apache.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        role: {{ .Values.apache.role }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.apache.image }}:{{ .Values.apache.imagetag }}"
          ports:
            - containerPort: {{ .Values.apache.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.apache.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.apache.internalPort }}
          env:
            - name: servicename
              value: {{ template "fullname" . }}-jeeservice:{{ .Values.jeeservice.externalPort }}
      imagePullSecrets:
          - name: {{ .Values.apache.imagesecret }}
          
