jeeapp:
  image: youracr.azurecr.io/demowas
  imagetag: latest
  imagesecret: regsecret
  internalPort: 9080
  role: backend
  replicaCount: 2

apache:
  image: youracr.azurecr.io/demoapache
  imagetag: latest
  imagesecret: regsecret
  internalPort: 80
  role: frontend
  replicaCount: 8

jeeservice:
  type: ClusterIP
  servicename: jeeservice
  externalPort: 8080
  internalPort: 9080
  
apacheservice:
  type: LoadBalancer
  servicename: apacheservice
  externalPort: 80
  internalPort: 80


